### ISSUE TITLE
[Bug] The keyboard don't pop up while New playlist

### ISSUE THREAD

**Issue by MrXBear** [zyrouge/symphony#373] opened 2023-12-21 12:02 UTC
### Description

The keyboard don't pop up while New playlist, even the input box is focused.

### Steps to Reproduce

Uninstall and reinstall Symphony App.
1. Go to 'playlists'
2. Click on '+ New playlist'
3. See error

### Expected Behavior

The keyboard pops up.

### Screenshots

![IMG_20231221_193943](https://github.com/zyrouge/symphony/assets/47053993/01a7dd6d-497c-49fa-8b9b-b561e3f8d2bd)

### Device

-   Device: Redmi
-   OS: Android 12
-   Version Symphoney v2023.11.107

### Additional Context

Sometime the keyboard can pop up, sometimes not.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2023-12-21 12:06
The keyboard cannot be opened again if you close the keyboard. For example, closing keyboard with back gesture, you cannot get keyboard up again by clicking on the input box. It might be helpful if you attach a clip or provide solid reproduction steps.

**Comment by MrXBear** [comment] 2023-12-21 12:30
https://github.com/zyrouge/symphony/assets/47053993/7257478f-69d5-4775-b7b1-a43f7ca5bbc7

Cannot open keyboard, until I navigate to 'Settings' and go back.

**Comment by zyrouge** [comment] 2023-12-24 14:20
> Screenrecorder.mp4
> 
> Cannot open keyboard, until I navigate to 'Settings' and go back.

Not sure what could possibly be happening. Unfortunately, I cannot reproduce this issue.

**Comment by Naul06** [comment] 2024-01-15 21:06
I can get aroud this by pasting the name I want, but yeah, it does happen just as @MrXBear says

**Comment by zyrouge** [comment] 2024-01-16 02:36
> I can get aroud this by pasting the name I want, but yeah, it does happen just as @MrXBear says

Which ROM/OS are you on?

**Comment by Naul06** [comment] 2024-01-16 17:21
Regular Android 10

**Comment by zyrouge** [comment] 2024-01-16 17:35
> Regular Android 10

Not sure what causes this. I currently do not to fix this since I'm not facing this.

**Comment by zyrouge** [comment] 2024-11-14 20:07
Seems like this issue has been fixed. Feel free to re-open if it isn't.

**Closed by zyrouge** 2024-11-14 20:07 UTC
Labels: type: bug, state: help wanted, reason: needs more info
