### ISSUE TITLE
[Bug] Improve search algorithm

### ISSUE THREAD

**Issue by Tansenstudy** [zyrouge/symphony#446] opened 2024-02-08 02:25 UTC
Search function not working properly 
When i search song it gives same result for every song i search

**Comment by zyrouge** [comment] 2024-02-08 02:26
The search seems to be inaccurate for partial search terms, which can be fixed by improving fuzzy search logic.

**Comment by RustoMCSpit** [comment] 2024-02-11 02:38
change issue title

**Comment by BigBoyBarney** [comment] 2024-03-08 10:45
Hi! Fantastic app, thanks!! I really love it.

This issue is my only "gripe" with it. I'm not sure how this issue could be solved, but perhaps putting direct partial matches above fuzzy matches would be a good temporary solution. The problem is illustrated below:
<img src="https://github.com/zyrouge/symphony/assets/86712892/4303da6a-3b4f-4762-80b6-b64788198fa6" width=30% height=30%>

<img src="https://github.com/zyrouge/symphony/assets/86712892/7872be26-53e6-4c64-8619-9373f4a48121" width=30% height=30%>

As you can see, the partial match "shiny smily" from "Shiny Smily Story (Bouquet ver.) does not even show up.

Additionally, it would be really cool if we could filter the search by adding the artist as well.

So for example to search for the song `Caesura of Despair by IRyS`, typing `caesura irys`. I'm not sure how difficult this would be to implement, but it would be cool!

Cheers!

**Comment by RustoMCSpit** [comment] 2024-03-15 16:55
any update on this?

**Comment by zyrouge** [comment] 2024-03-15 16:57
> any update on this?

I'm busy as of now, any updates are likely to be delayed.

**Closed** 2024-04-19 08:50 UTC
Labels: type: bug, state: done

**Comment by BigBoyBarney** [comment] 2024-04-20 10:54
Works like a charm. Thank you so much for this! Massive QoL update!! <3

**Comment by BigBoyBarney** [comment] 2024-04-22 14:06
# Edit
The change fixes latin character search, but completely breaks CJK, see screenshots below:

### As you can see, CJK characters are not matched at all.

<img src="https://github.com/zyrouge/symphony/assets/86712892/ec2efaf7-6598-4b1e-a215-59a89848ea5b" width=30% height=30%>
<img src="https://github.com/zyrouge/symphony/assets/86712892/0ce9d1b7-4792-4e05-a1a8-f916dc684a9c" width=30% height=30%>
<img src="https://github.com/zyrouge/symphony/assets/86712892/ab921843-dd9b-413d-88a2-7e097892c285" width=30% height=30%>

----

### A couple more examples:

<img src="https://github.com/zyrouge/symphony/assets/86712892/1ad99beb-c1de-4c73-b175-3f4292ba7dbb" width=30% height=30%>
<img src="https://github.com/zyrouge/symphony/assets/86712892/c198e09d-a61d-42bc-b3cb-907b0399bd2a" width=30% height=30%>

-----

### This seems to be the "default" match when searching for a whitespace (the same as with any pure CJK search)

<img src="https://github.com/zyrouge/symphony/assets/86712892/5d0f5b00-e7e7-4279-8063-901450f7fe75" width=30% height=30%>

-----

I can't reopen this issue. Should I submit a new one, or will you reopen it? I understand that this might be a low priority feature for most users, but it is quite essential in mine 🤣.

Cheers!

**Comment by zyrouge** [comment] 2024-04-22 14:14
Kindly open a new issue.
