### ISSUE TITLE
[Bug] App Crash Unknown Reason 

### ISSUE THREAD

**Issue by FreeAndFrei** [zyrouge/symphony#406] opened 2024-01-06 07:10 UTC
### Description

I was probably switching from WiFi to Mobile Data when I clicked the ''start'' button. And the App Crashed and gave me error s like: 

### Steps to Reproduce

I don't know :(

### Screenshots

![Screenshot_20240106_150013_Symphony.png](https://github.com/zyrouge/symphony/assets/113665446/31ded85d-7fb8-4499-ac98-79fd9c551cc3)

![Screenshot_20240106_150008_Symphony.png](https://github.com/zyrouge/symphony/assets/113665446/6eef64f3-e1ab-4bc8-a029-eab6ed13c3a9)

### Device

-   Device: Samsung S22 Chinese Version
-   OS: Android 13

**Comment by zyrouge** [comment] 2024-01-07 07:10
Unfortunately, that stack trace is unusable due to obfuscation. Unless there are solid steps to reproduce this, I'm unable to help. Let me know if that occurs frequently.

**Comment by pushpulldecoder** [comment] 2024-02-03 20:16
Could you also add obfuscation map with releases, maybe with future releases

**Comment by zyrouge** [comment] 2024-11-14 20:08
Closing this in favor of #504.

**Closed by zyrouge** 2024-11-14 20:08 UTC
Labels: type: bug, reason: needs more info
