### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Lucky390163** [zyrouge/symphony#324] opened 2023-11-11 12:55 UTC
I can not search my songs when i type artist name in search bar i have many songs of their and this app only displays 5 or 5.

And it cannot displays album of them.![Screenshot_20231111_183325_Symphony.jpg](https://github.com/zyrouge/symphony/assets/115852216/37a121f7-289a-463a-a663-25c2b9c1a277)

![Screenshot_20231111_183319_Poweramp.jpg](https://github.com/zyrouge/symphony/assets/115852216/027ad58f-e9a6-43bb-b07b-b5f995393492)

**Comment by zyrouge** [comment] 2023-11-11 13:20
Could you be more clear? Search can actually search depending upon songs, artists, albums, etc. The songs are sorted using the song's name and not artist's name. You can also view the album by clicking the options icon > view album. If you need to view details of certain artist, they are listed in the artist's page already. You cannot expect the songs to be matched using artist's name when it should be matched according to the song's name. Closing this as working as intended.

**Closed by zyrouge** 2023-11-11 13:20 UTC
Labels: type: enhancement
