### ISSUE TITLE
Symphony has no access to my folders tree

### ISSUE THREAD

**Issue by serrq** [zyrouge/symphony#85] opened 2023-03-13 07:40 UTC
Even with media permission allowed it doesn't view anything.

Must I give it full tree folders permission?

Android 12
OnePlus CPH2399
Symphony 2023.3.73 f-droid repo

**Comment by zyrouge** [comment] 2023-03-13 11:03
> Even with media permission allowed it doesn't view anything.
> 
> Must I give it full tree folders permission?
> 
> Android 12 OnePlus CPH2399 Symphony 2023.3.73 f-droid repo

Does the songs get listed in the songs page? Also check if the paths in song information is correct.

**Comment by zyrouge** [comment] 2023-03-15 11:11
Not sure what that is. These the required permissions for the app.

![Screenshot_2023-03-15-16-40-11-100_com google android permissioncontroller](https://user-images.githubusercontent.com/50770114/225292181-99dc7979-1cae-4ac1-a701-105b23ed7891.jpg)

**Comment by zyrouge** [comment] 2023-03-16 16:27
You could refer [this](https://developer.android.com/training/data-storage/shared/media). Also could you try messing up with storage access?

**Comment by zyrouge** [comment] 2023-03-16 16:43
> I have no idea what you’re asking me to do. I’ve given permissions but I don’t see the directories.

You don't see the directories because the app cannot see it. It's either an issue with permission or issue with your MediaStore.

**Comment by zyrouge** [comment] 2023-03-17 01:04
> Add the "all files" permission optionally and you bypass the problem.
> 
> PS: SAF picker might works in this case?

SAF picker has way more limitations, which is why it isn't used. Also "all files" permission might not be the solution.

**Comment by zyrouge** [comment] 2023-03-17 15:53
> Sorry I don't use Discord. Do you have SimpleX?

Sadly no.

**Comment by zyrouge** [comment] 2023-04-11 15:02
Closing this since it's not reproducible.

**Closed by zyrouge** 2023-04-11 15:02 UTC
Labels: question, waiting for response

**Comment by FortuneSeller** [comment] 2023-06-10 10:43
im having the exact same issue

**Comment by zyrouge** [comment] 2023-06-10 13:59
> im having the exact same issue

Could you open a new issue? It's better if you could discuss this in the Discord server.
