### ISSUE TITLE
Swiping for navigation

### ISSUE THREAD

**Issue by sojusnik** [zyrouge/symphony#38] opened 2023-02-20 21:27 UTC
Nowadays, swiping is getting more and more popular for navigation within Android. One way to make navigation within your great app more intuitive is by adding a swiping up gesture in the area where the bottom panel and the mini-player are. A quick swipe up there would open the "now playing" view. And a quick swipe up in the "now playing" view would open the queue, while a swipe down in the "now playing" view would bring you back to your initial view, like folders, albums etc. Swiping down on the area at the top, where "queue" is written, would bring you back to the "now playing" view.

**Comment by zyrouge** [comment] 2023-02-21 00:58
Duplicate of #18.

**Closed by zyrouge** 2023-02-21 00:58 UTC
