### ISSUE TITLE
[Bug] The pitch thing needs serious working. The song distorts and I cannot set my own, have to rely on preset.

### ISSUE THREAD

**Issue by Varniit-pro-90s** [zyrouge/symphony#435] opened 2024-01-28 20:36 UTC
### Description

A clear and concise description of what the bug is
[Bug] The pitch thing needs serious working. The song distorts and I cannot set my own, have to rely on preset.

### Screenshots

![Screenshot_2024-01-29-01-57-58-026_io github zyrouge symphony](https://github.com/zyrouge/symphony/assets/156216269/460478a4-d489-408b-aebd-b87be4ab6c49)
![Screenshot_2024-01-29-01-58-04-137_io github zyrouge symphony](https://github.com/zyrouge/symphony/assets/156216269/b24feaa2-df15-406d-96ed-bbaf2f827169)
![Screenshot_2024-01-29-01-58-17-637_io github zyrouge symphony](https://github.com/zyrouge/symphony/assets/156216269/a49e4a44-f7ec-4adc-ade9-2db57c03efa3)
![Screenshot_2024-01-29-02-00-22-723_in krosbits musicolet](https://github.com/zyrouge/symphony/assets/156216269/5daebc53-e549-4b8f-ba7e-8b46f35fe5ed)
![Screenshot_2024-01-29-02-00-28-207_in krosbits musicolet](https://github.com/zyrouge/symphony/assets/156216269/3c38217a-94e4-49a8-a6a3-46d2df7dc740)
![Screenshot_2024-01-29-02-00-33-982_in krosbits musicolet](https://github.com/zyrouge/symphony/assets/156216269/d3fc0465-4e39-4f87-b0db-a75ef4d50472)

### Device

-   Device: [e.g. Google Pixel 6]
- Xiaomi Redmi Note 5, 10 and 11
-   OS: [e.g. Android 13]
- Android 9, 11 and 13
-   Version [e.g. 2023.04.20]
- 2024.1.109

### Additional Context

Added screenshots of another music app "musicolet", I have been using for years. See how it does pitch and speed thing in finer way.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2024-01-29 01:47
Duplicate of #111.

**Closed by zyrouge** 2024-01-29 01:47 UTC
Labels: type: bug
