### ISSUE TITLE
[Bug] App Crash

### ISSUE THREAD

**Issue by Chr0matic1** [zyrouge/symphony#184] opened 2023-06-05 23:25 UTC
### Description

Entered the app, played a file and skipped a bit, left the app and playback suddenly stopped, was greeted by the screen below upon entering.

### Steps to Reproduce

-

### Expected Behavior

-

### Screenshots

![Screenshot_20230606_011657_Symphony](https://github.com/zyrouge/symphony/assets/101169615/3cffd30c-5590-40b8-92a7-7f7176d2ee6f)
![Screenshot_20230606_011704_Symphony](https://github.com/zyrouge/symphony/assets/101169615/8f5957d1-b50a-47ca-9445-a6539431f896)

### Device

-   Device: Galaxy A52s 5G
-   OS: Android 13
-   Version 2023.06.93

### Additional Context

-

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2023-06-06 03:22
Does this occur often? This error is caused by service not being started, this error cannot be caught as well.

**Comment by Chr0matic1** [comment] 2023-06-06 10:20
Well it happened again, so twice today but I never had this problem before.

**Comment by zyrouge** [comment] 2023-06-06 10:23
> Well it happened again, so twice today but I never had this problem before. I enter the app, play a song, back out and it crashes.

Could you attach a clip?

**Comment by ghostnear** [comment] 2023-09-11 21:55
Managed to recreate this on my LineageOS device. I am looking around to see what actually causes this.

Until then, here's a recording of it happening:

[untitled.webm](https://github.com/zyrouge/symphony/assets/92169032/9a908f38-372e-4a9f-bb85-ba7d27739093)

**Comment by zyrouge** [comment] 2023-09-12 01:13
> Managed to recreate this on my LineageOS device. I am looking around to see what actually causes this.
> 
> Until then, here's a recording of it happening:
> 
>  untitled.webm 
> (it worked fine for like 30 seconds before audio stopped and app crashed)

https://developer.android.com/guide/components/foreground-services#background-start-restrictions. I don't think there is a way to handle this error, but let me know if it is preventable.

**Comment by zyrouge** [comment] 2023-12-04 17:07
Closing this since it's just how notifications work in Android. There have been fixes implemented on recent versions, so I don't think this is relevant anymore.

**Closed by zyrouge** 2023-12-04 17:07 UTC
Labels: type: bug, state: wont fix
