### ISSUE TITLE
[Bug] Searching for track name or artist returns all songs, rather than match(es) only

### ISSUE THREAD

**Issue by Fironet** [zyrouge/symphony#238] opened 2023-08-12 10:16 UTC
### Description

Performing a search for either a track name or artist name returns all music rather than filtering to only display matches to the query.

### Steps to Reproduce

1. Click on the search button in the top-left.
2. Enter a track or artist name.
3. Observe the results.

### Expected Behavior

The results should only return matches to the query.

### Screenshots

![1](https://github.com/zyrouge/symphony/assets/6971981/0bf67ea1-7f6a-4d82-bb25-49f3dc453e8c) ![2](https://github.com/zyrouge/symphony/assets/6971981/120944be-e9f1-4633-8962-f668adf5056d) ![3](https://github.com/zyrouge/symphony/assets/6971981/9fb01ab4-4e6b-4298-a041-e06abbf77d02)

### Device

-   Device: Google Pixel 4a 5G
-   OS: LineageOS 20 (Android 13)
-   Version: v2023.8.105 (via F-Droid)

### Additional Context

For reference in the screenshots above:

- When taking the first screenshot I had just one album on the device.
- For the second two screenshots I had two albums on the device, both by the artist Modeselektor. 10 tracks across two albums. 1 track of one album has multiple artist tags per track, while 3 of the other album do too (not sure if relevant).
- The query `flohio` is a featured artist of only one of the songs on an album, yet one can see the query returns other tracks from the album, too.
- The query `50 trees` returns tracks from both albums, and when selecting the *Albums* filter button it returns both albums, too.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2023-08-12 17:30
The algorithm isn't very capable of differentiating words that much. It just tries matching letter orders and sort it with the computed score, the first 10 results are returned after it. So if you have only 10 songs, 10 results will be shown ranking best match to no match. This is the intended behaviour. Closing this as intended behaviour. Feel free to open PR to have better searching algorithms.

**Comment by Fironet** [comment] 2023-08-13 07:41
> 10 results will be shown ranking best match to no match.

Would it be possible to hide results that have no match? If what you mean is it returns results by closest score/percent match(es) in descending order, until effectively '0', could the '0' rank matches be hidden?

Like, in the `flohio` example above, I'd assume that no other tracks/albums would have a ranking score besides the first result, since it's a unique string that only appears in one track's tags. Though I'm not sure how the algo works.

**Comment by zyrouge** [comment] 2023-08-13 07:50
The algorithm cannot do it precisely. It's a fuzzy search algorithm. Maybe checking the difference in ranks could help this. I'll keep this open until then.

**Closed** 2023-11-24 09:05 UTC
Labels: type: bug, state: done
