### ISSUE TITLE
[Feature Request] Change the order of songs in playlist

### ISSUE THREAD

**Issue by RomgoTM** [zyrouge/symphony#289] opened 2023-10-12 16:10 UTC
Hello, the app is just great!!! But unfortunately, it's not ideal. Can you add a function to change the order of songs in playlists?
It would be very cool

**Comment by Heus-Sueh** [comment] 2023-10-25 13:01
duplicate of issue #130

**Comment by zyrouge** [comment] 2023-10-25 13:13
> duplicate of issue #130

Seems like it. Closing this in favor of #130.

**Closed by zyrouge** 2023-10-25 13:13 UTC
Labels: type: enhancement, state: help wanted, priority: medium
