### ISSUE TITLE
[Bug] Only the last line is synchronized on .lrc lyrics

### ISSUE THREAD

**Issue by Nadim147c** [zyrouge/symphony#499] opened 2024-03-31 11:36 UTC
### Description

As you can see only the last line of lyrics (from .lrc) is synchronized. The lyrics remain on the second last line and go to the last line at the end.

### Steps to Reproduce

1. Play any song with .lrc lyrics
2. Go now playing and open lyrics

### Expected Behavior

The entire lyrics are supposed to be synchronized.

### Screenshots

![Screenshot_2024-03-31-17-24-57-69_c328a126cb0fb561391a2f6f61559b68](https://github.com/zyrouge/symphony/assets/90786729/9846270d-aed3-4fac-b515-508678603bfc)
![Screenshot_2024-03-31-17-19-33-93_c328a126cb0fb561391a2f6f61559b68](https://github.com/zyrouge/symphony/assets/90786729/e468f523-57ad-4067-89d8-787800df8368)

### Device

-   Device: Realme Narzo 50
-   OS: Android 13
-   Version: v2024.3.111-nightly+8a1472a

### Additional Context

I don't know if it happens with Embedded lyrics or not

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2024-03-31 11:37
Could you send the `.lrc` file's content?

**Comment by Nadim147c** [comment] 2024-03-31 13:10
Sure

```
[00:00.48]Ooh ooh-ooh
[00:04.54]Ooh-ooh-ooh
[00:05.74]Just can't believe this man
[00:07.04]Metro Boomin want some more n***a
[00:10.85]Somebody said they saw you
[00:15.65]The person you were kissing wasn't me
[00:20.53]And I would never ask you
[00:25.64]I just kept it to myself
[00:28.26]I don't wanna know
[00:31.26]If you're playin' me keep it on the low
[00:36.08]'Cause my heart can't take it anymore
[00:40.84]And if you're creepin' please don't let it show
[00:45.90]Oh baby I don't wanna know
[00:49.98]Oh-oh oh-oh oh-woah
[00:53.75]Oh-oh oh-oh oh-oh
[00:57.63]Oh yeah
[00:59.30]I think about it when I hold you
[01:04.59]When lookin' in your eyes I can't believe
[01:09.52]And I don't need to know the truth
[01:14.64]Baby keep it to yourself
[01:17.26]I don't wanna know
[01:20.24]If you're playin' me keep it on the low
[01:25.09]'Cause my heart can't take it anymore
[01:29.61]And if you're creepin' please don't let it show
[01:34.88]Oh baby I don't wanna know
[01:38.95]Did he touch you better than me
[01:40.63]Touch you better than me
[01:41.69]Did he watch you fall asleep
[01:43.11]Watch you fall asleep
[01:43.95]Did you show him all those things that you used to do to me
[01:48.71]If you're better off that way
[01:50.23]Better off that way
[01:51.27]There ain't more that I can say
[01:52.90]More that I can say
[01:53.96]Just go on and do your thing and don't come back to me
[01:58.21]Ooh ooh-ooh
[02:01.86]Ooh-ooh-ooh
[02:04.11]Woah woah woah 21
[02:07.71]Had me questioned I was cuffin' like the precinct
[02:10.10]How you go from housewife to a sneaky link
[02:12.52]Got you riding 'round in all type of Benzes and Rovers
[02:15.38]Girl you used to ride in the rinky dink
[02:17.52]I'm the one put you on Elliantte
[02:19.28]On God
[02:19.83]Fashion Nova model I put you on the runway
[02:21.81]On God
[02:22.13]You was rockin' coach bags got you Chane'-ne'
[02:24.50]Sad ***** in Fresco I call her my baby
[02:26.63]21
[02:27.15]I got a girl but I still feel alone
[02:29.14]On God
[02:29.34]If you playin' me that mean my home ain't home
[02:31.53]On God
[02:31.94]Havin' nightmares of goin' through your phone
[02:33.97]21
[02:34.34]Can't even record you got me out my zone
[02:35.98]I don't wanna know
[02:38.49]If you're playin' me keep it on the low
[02:43.41]'Cause my heart can't take it anymore
[02:48.14]And if you're creepin' please don't let it show
[02:53.35]Oh baby I don't wanna know
[02:58.23]If you're playin' me keep it on the low
[03:03.04]'Cause my heart can't take it anymore
[03:07.74]And if you're creepin' please don't let it show
[03:12.86]Oh baby I don't wanna know
[03:21.05]If you creepin' just don't let me find out
[03:22.84]On God
[03:23.48]Get a hotel never bring 'em to the house
[03:25.46]On God
[03:26.57]If you're better off that way
[03:29.13]Baby all that I can say
[03:31.48]If you're gonna do your thing then don't come back to me
```

**Comment by zyrouge** [comment] 2024-04-17 07:46
![image](https://github.com/zyrouge/symphony/assets/50770114/dc2ce043-5f73-4def-bb05-1070e02146b5)

Seems to be working fine for me.

**Comment by zyrouge** [comment] 2024-04-17 07:47
Closing this, feel free to re-open if needed.

**Closed by zyrouge** 2024-04-17 07:47 UTC
Labels: type: bug, state: triage

**Comment by Ue05** [comment] 2024-04-27 15:27
I had the same problem, but the cause was that the line feed code was not LF. If I set the linefeed code to LF, it synchronizes correctly.
