### ISSUE TITLE
[Bug] Shuffle displays wrong song

### ISSUE THREAD

**Issue by WX580** [zyrouge/symphony#179] opened 2023-06-02 07:20 UTC
Upon turning on shuffle songs will shuffle as normal but the screen showing what songs are playing goes in whatever way you have your music sorted and shows all the wrong songs 
![Screenshot_20230602-031822_Symphony](https://github.com/zyrouge/symphony/assets/119598169/5fe1ca21-2ccc-4594-bb75-e247e10b8aa0)
![Screenshot_20230602-031825_Symphony](https://github.com/zyrouge/symphony/assets/119598169/b592e3d2-23b9-49d6-8f51-d0479ba488c3)
Upon turning off shuffle it will show the correct song but not shuffle anymore

**Comment by zyrouge** [comment] 2023-06-02 08:03
Are you on latest version? I cannot seem to reproduce this issue. Could you attach a clip?

**Comment by WX580** [comment] 2023-06-02 16:02
> Are you on latest version? I cannot seem to reproduce this issue. Could you attach a clip?

It seems to have managed to fix itself, i should be on the latest version i just downloaded it from f-droid

**Comment by zyrouge** [comment] 2023-06-02 16:04
> > Are you on latest version? I cannot seem to reproduce this issue. Could you attach a clip?
> 
> It seems to have managed to fix itself, i should be on the latest version i just downloaded it from f-droid

F-droid updates take at least 3-5 days after Github Releases. Closing this since it has already been fixed.

**Closed by zyrouge** 2023-06-02 16:04 UTC
Labels: bug

**Comment by zyrouge** [comment] 2023-06-02 16:06
Fyi, F-droid release is currently 2 updates behind latest release in Github Releases.
