### ISSUE TITLE
[Feature Request] Keep music playing when closing Symphony

### ISSUE THREAD

**Issue by Krintni** [zyrouge/symphony#382] opened 2023-12-28 20:40 UTC
### Description

Currently Symphony only plays music while the app is kept in the recent apps menu. If one removes Symphony from recent apps by swiping the music stops and the media player notification disappears. It's inconvenient because one has to make sure not to close Symphony by accident. 

### Solution
Music and the media player notification should stay active after closing Symphony unless the queue/current song is dismissed. Maybe this could be achieved with a permanent notification for music control. 

### Additional Context

On ChromeOS the lack of a permanent notification appears to prevent the native media player panel from picking up the current song. But that's just my observation when comparing with VLC for Android which does have a permanent notification.

### Checklist

-   [X] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2024-01-11 12:56
This is intended behavior. The app does not run in background if *you* close it.

**Comment by alijafari-gd** [comment] 2024-01-15 05:21
> This is intended behavior. The app does not run in background if _you_ close it.

can you make it like a foreground service , ? because android users usually use that Close All button

**Comment by zyrouge** [comment] 2024-01-15 05:24
> > This is intended behavior. The app does not run in background if _you_ close it.
> 
> can you make it like a foreground service , ? because android users usually use that Close All button

That might require modification of the existing playback mechanism. Also, it is not idea of create a foreground service since it might be battery intensive considering the amount of work the app does.

**Comment by zyrouge** [comment] 2024-11-14 20:16
The easiest fix for this will be to not close the app from recents. This has been discussed a lot and the decision says as is.

**Closed by zyrouge** 2024-11-14 20:16 UTC
Labels: type: enhancement, reason: needs more info

**Comment by Holbormon** [comment] 2024-12-02 05:05
> That might require modification of the existing playback mechanism. Also, it is not idea of create a foreground service since it might be battery intensive considering the amount of work the app does.

I'm not sure I understand that rationale, since the vast majority of music player apps work in the background: that's precisely their point. Also, users might take great care not to close the app from the recents, but every Android-based OS is different and some of them might be more aggressive with non-persistent background tasks, and close them anyway after a while.

To me, this app has the potential to become the best FOSS music player out there, because it is truly innovative instead of forking the same main player design over and over like all other apps out there. However, design choices like this one make it hard to adopt as a daily driver.

**Comment by Holbormon** [comment] 2024-12-09 10:56
> Also, it is not idea of create a foreground service since it might be battery intensive considering the amount of work the app does.

Not sure if this is a bug that deserves an issue of its own, too, but the app already seems more battery intensive than most players out there as is:
![Screenshot_20241205-191931_1](https://github.com/user-attachments/assets/831c9eae-a730-4bc2-b0c0-03d4ad5a15d5)

**Comment by zyrouge** [comment] 2024-12-09 11:03
> > Also, it is not idea of create a foreground service since it might be battery intensive considering the amount of work the app does.
> 
> Not sure if this is a bug that deserves an issue of its own, too, but the app already seems more battery intensive than most players out there as is: ![Screenshot_20241205-191931_1](https://private-user-images.githubusercontent.com/160845407/393807083-831c9eae-a730-4bc2-b0c0-03d4ad5a15d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDIyMzQsIm5iZiI6MTczMzc0MTkzNCwicGF0aCI6Ii8xNjA4NDU0MDcvMzkzODA3MDgzLTgzMWM5ZWFlLWE3MzAtNGJjMi1iMGMwLTAzZDRhZDVhMTVkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxMDU4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTFkYzMwNTA0ODg1NmUyNWEyYjc4YTE1NjU3MzE2NjA3MzgyMzE5YjBiMGMxODY0NTc0ODA4MWQ5Yjk4OGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9Of_wagGN1BXgdZw3wgccvSQ89-vYN9GovHyiQUbn_0)

Sure. I'm neither sure about the performance metrics of other players nor have I measured how much battery Symphony consumes. Will be curious to know those!

**Comment by 1RandomDev** [comment] 2024-12-09 15:30
Can we please add this, Symphony is awesome, but I always close my recent apps and later forget to open Symphony again before driving which means I can't start the music via bluetooth.
