### ISSUE TITLE
[Feature Request] Support for aac, flac and ogg

### ISSUE THREAD

**Issue by sojusnik** [zyrouge/symphony#39] opened 2023-02-20 21:30 UTC
Is it an easy task to support audio formats like aac, flac and ogg? These are common these days and a lot of other players can open them. Would be awesome, if your player could play them too.

**Comment by zyrouge** [comment] 2023-02-21 01:09
According to [this](https://developer.android.com/guide/topics/media/media-formats), they are supported by default. I'll confirm it once I test it myself.

**Comment by sojusnik** [comment] 2023-02-21 15:38
My bad! Through the folders view those formats are shown and can be played, but when taping on a file in Android's file browser, then you can't play them, even mp3, because your player isn't listed there. So it's a bug about your app not appearing in the list of potential apps to open an audio file.

**Comment by zyrouge** [comment] 2023-02-21 16:19
> My bad! Through the folders view those formats are shown and can be played, but when taping on a file in Android's file browser, then you can't play them, even mp3, because your player isn't listed there. So it's a bug about your app not appearing in the list of potential apps to open an audio file.

That's because I haven't implemented that yet. The focus was to browse everything through the app, thus it was never implemented and will probably never be. I might do that if enough people requests it, but now, it will not be possible. Closing this since it is not a bug.

**Closed by zyrouge** 2023-02-21 16:19 UTC
Labels: enhancement
