### ISSUE TITLE
[Bug] Music stops playing when closing app

### ISSUE THREAD

**Issue by ghost** [zyrouge/symphony#556] opened 2024-05-28 15:14 UTC
### Description

When the app is closed, playback is stopped. This is not the expected behavior of a music player.

### Steps to Reproduce

1. Start playing a song
2. Open the recent app list
3. Close the app
4. Music stops playing

### Expected Behavior

The music continues playing even when the app is closed.

### Device

-   Device: Samsung Galaxy S21 Ultra
-   OS: Android 11
-   Version 2024.3.110 (F-Droid)

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2024-06-04 15:17
Duplicate of #382.

**Closed by zyrouge** 2024-06-04 15:17 UTC
Labels: type: bug
