### ISSUE TITLE
Offline app "have full network access"

### ISSUE THREAD

**Issue by serrq** [zyrouge/symphony#84] opened 2023-03-13 07:35 UTC
Please remove unnecessary and suspicious permissions.

![45009](https://user-images.githubusercontent.com/113377431/224635904-9cc6f0a8-9d35-455b-8af3-4baddf5ae5d1.jpg)

**Comment by timothykumm** [comment] 2023-03-13 10:25
Symphony is checking for new updates

**Comment by zyrouge** [comment] 2023-03-13 11:02
> Symphony is checking for new updates

This is the exact reason. To check for new version. Closing this since it is intended. Let me know if you have any more clarification.

**Closed by zyrouge** 2023-03-13 11:02 UTC

**Comment by zyrouge** [comment] 2023-03-13 12:05
> I have fdroid version so I don't need of check for update.

Just disable check for updates. Different flavors are not used for F-droid release since I need reproducible builds using same signature, nor does Android support denying internet option.

**Comment by zyrouge** [comment] 2023-03-13 12:33
> Just remove the written "offline app". Replacing with "sometime it goes online in order to check for update".

I probably should do that.
