### ISSUE TITLE
[Feature Request] Add support for .m3u format playlists

### ISSUE THREAD

**Issue by S-Sajith** [zyrouge/symphony#13] opened 2022-12-10 18:42 UTC
Please add .m3u file format playlist support, as it eases the migration process from other music players across different platforms easier.

**Comment by S-Sajith** [comment] 2023-02-08 14:35
![Screenshot_20230208-200428.png](https://user-images.githubusercontent.com/88919814/217560088-5a2a9eb2-1d2d-44ed-b8a7-7f9fc1a396e8.png)

I get this error when importing an existing .m3u playlsit

**Comment by zyrouge** [comment] 2023-02-08 14:40
Could you attach a video footage?

**Comment by S-Sajith** [comment] 2023-02-08 15:06
I don't have the version of the app with this bug installed , I too rolled back to the previous version

**Comment by zyrouge** [comment] 2023-02-08 15:21
> I don't have the version of the app with this bug installed , I too rolled back to the previous version . I can share the playlist files if required

I guess I'll rerolled the release. Please attach a video footage if possible after that.

**Comment by zyrouge** [comment] 2023-02-08 15:36
Seems like this could indeed by caused by an unparsable M3U file. I've implemented a fix for this in the upcoming release. Could you send the M3U file?

**Comment by S-Sajith** [comment] 2023-02-08 15:52
> Seems like this could indeed by caused by an unparsable M3U file. I've implemented a fix for this in the upcoming release. Could you send the M3U file?

[Link to playlisy Files](https://mega.nz/folder/wwNVyJ4C#4yqz0iVSSZ0qEJT_XfLrvQ)

**Comment by zyrouge** [comment] 2023-02-08 16:42
> > Seems like this could indeed by caused by an unparsable M3U file. I've implemented a fix for this in the upcoming release. Could you send the M3U file?
> 
> [Link to playlist Files](https://mega.nz/folder/wwNVyJ4C#4yqz0iVSSZ0qEJT_XfLrvQ)

Seems like absolute paths broke it. Pushed a fix on v2023.2.62. I'll be closing this now. Let me know if there are more issues.

**Closed by zyrouge** 2023-02-08 16:42 UTC
Labels: enhancement
