### ISSUE TITLE
[Bug] Sorting in queue interrupt the playlist

### ISSUE THREAD

**Issue by Banh7** [zyrouge/symphony#403] opened 2024-01-04 19:01 UTC
https://drive.google.com/file/d/1GuB71eks9Pn_CTCBETYOyU9FGxLY6pkT/view?usp=drivesdk

### Device

-   Device: Oppo A77s
-   OS: Android 13
-   Version: v2024.1.109-nightly+e44b7b6

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2024-01-05 02:21
That is not a sort button, it's a clear queue option. Closing this since it is not a bug.

**Closed by zyrouge** 2024-01-05 02:21 UTC
Labels: type: bug

**Comment by Banh7** [comment] 2024-01-05 15:48
Oh srry. I thought it was sort button
