### ISSUE TITLE
"Add to playlist" is missing in the 3 dots menu in the albums view

### ISSUE THREAD

**Issue by sojusnik** [zyrouge/symphony#36] opened 2023-02-20 21:03 UTC
If you tap on the 3 dots menu of an album in the albums view, then you'll see that "add to playlist" is missing there, although you could add the album to the queue.

**Comment by zyrouge** [comment] 2023-02-21 01:04
Duplicate of #24.

**Closed by zyrouge** 2023-02-21 01:04 UTC
