### ISSUE TITLE
Error: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by eleius** [zyrouge/symphony#696] opened 2024-12-04 06:41 UTC
### Description

Sometimes I got this error while playing songs in Symphony (see screenshot)

### Steps to Reproduce

Seems to happen randomly (not often) while playing songs.

### Expected Behavior

-

### Screenshots

![Screenshot_20241203-115913_Trebuchet_1](https://github.com/user-attachments/assets/0fc386a8-6162-4daa-91f9-4d66a6410d64)

### OS

LineageOS 21 (Android 14)

### Version

2024.11.114

### Contribution Guidelines

- [X] I agree to follow the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2024-12-05 05:22
Duplicate of #504.

**Closed** 2024-12-05 05:22 UTC
Labels: type: bug, reason: duplicate
