### ISSUE TITLE
[Bug] playlist import and export issues, as well as some missing features.

### ISSUE THREAD

**Issue by Snapxxx12** [zyrouge/symphony#636] opened 2024-11-03 23:16 UTC
1. Symphony cannot import playlists exported from other applications.

2. In the imported playlist menu, the appearance is different from the playlist created directly from the Symphony application. In the imported playlist menu, the export and rename options are missing, whereas in a playlist created directly in the Symphony app, all menus appear in full.

https://github.com/user-attachments/assets/330c349a-ce88-438e-b139-74b312a089ae

**Comment by zyrouge** [comment] 2024-11-06 20:08
Closing this as duplicate of #633.

**Closed by zyrouge** 2024-11-06 20:08 UTC
