### ISSUE TITLE
[Bug] Crash when all songs are removed from the queue 

### ISSUE THREAD

**Issue by nsde** [zyrouge/symphony#195] opened 2023-06-18 08:50 UTC
### Description

This one should be easy to fix. 

### Steps to Reproduce

When all songs, including the one playing are removed from the current queue, the app crashes

### Expected Behavior

No crash lmao

### Screenshots

![Screenshot_2023-06-18-10-48-02-159_io.github.zyrouge.symphony.jpg](https://github.com/zyrouge/symphony/assets/67185896/ceb4ce73-cc51-482f-95a0-a8ae38f6d3d7)
![Screenshot_2023-06-18-10-48-56-110_io.github.zyrouge.symphony.jpg](https://github.com/zyrouge/symphony/assets/67185896/60cc8f65-539e-4ba3-847a-57f5fec1c34b)

### Device

-   Device: Poco X3 Pro
-   OS: Android 11
-   Version: 2023.6.93

### Additional Context

-

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2023-06-18 09:01
I'm unable to reproduce this issue. Could you attach a clip?

**Comment by nsde** [comment] 2023-06-18 09:32
> I'm unable to reproduce this issue. Could you attach a clip?

Sure, gimme a sec

**Comment by nsde** [comment] 2023-06-18 09:39
Sorry, I just noticed I described the issue somewhat inaccurately. Anyways, here's the link:

**Comment by nsde** [comment] 2023-06-18 09:39
https://ufile.io/z2u7vyxe

**Comment by zyrouge** [comment] 2023-06-18 18:00
Was able to reproduce this issue. Thanks for the clip.

**Comment by SimoLRepo** [comment] 2023-07-03 10:47
A similar error is <a href="https://github.com/zyrouge/symphony/issues/208">reported here</a>

**Comment by BenDundon** [comment] 2023-07-08 09:13
I have this same issue. I think I know the cause. This happens when you remove multiple items, and one of those items is the final item in the playlist. This causes the Index out of bounds error seen below, as the size of the array changes when the previous songs are removed. ![Screenshot_2023-07-08-19-01-48-11_c328a126cb0fb561391a2f6f61559b68.jpg](https://github.com/zyrouge/symphony/assets/30951911/712c39e8-54c2-4580-9f26-43ef2d4d1b68)

Say for example my queue is 14 elements long. I remove the last 3 elements (12, 13, 14), queue goes like this

[..., 11 (song a), 12 (song b), 13 (song c), 14 (song d)] -> remove song b in position 12

[..., 11 (song a), 12 (song c), 13 (song d)] -> remove song c in position 13 (this is no longer true)

[..., 11 (song a), 12 (song c)] -> remove song d in position 14 (this is no longer true, and is out of range)

I suspect this could be fixed by iterating backwards instead? e.g., remove 14, 13, 12 instead of 12, 13, 14?

**Comment by zyrouge** [comment] 2023-07-09 03:33
> I have this same issue. I think I know the cause. This happens when you remove multiple items, and one of those items is the final item in the playlist. This causes the Index out of bounds error seen below, as the size of the array changes when the previous songs are removed. ![Screenshot_2023-07-08-19-01-48-11_c328a126cb0fb561391a2f6f61559b68.jpg](https://user-images.githubusercontent.com/30951911/251963851-712c39e8-54c2-4580-9f26-43ef2d4d1b68.jpg)
> 
> Say for example my queue is 14 elements long. I remove the last 3 elements (12, 13, 14), queue goes like this
> 
> [..., 11 (song a), 12 (song b), 13 (song c), 14 (song d)] -> remove song b in position 12
> 
> [..., 11 (song a), 12 (song c), 13 (song d)] -> remove song c in position 13 (this is no longer true)
> 
> [..., 11 (song a), 12 (song c)] -> remove song d in position 14 (this is no longer true, and is out of range)
> 
> I suspect this could be fixed by iterating backwards instead? e.g., remove 14, 13, 12 instead of 12, 13, 14?

Changes in indices are handled.
https://github.com/zyrouge/symphony/blob/00b5b68e118b70d82ef1a1c703740ad7db48e113/app/src/main/java/io/github/zyrouge/symphony/services/radio/RadioQueue.kt#L93.

**Comment by BenDundon** [comment] 2023-07-09 04:49
> Changes in indices are handled.

Oh ok, never mind I'm not sure then. 
Have just done further testing and it definitely only seems to occur when the selected songs includes a song that would become out of range after the previous ones are removed in the way I described, but your implementation looks like it should be avoiding that just fine...

**Comment by zyrouge** [comment] 2023-07-31 17:31
:tada: Fixed as of v2023.7.104!

**Closed by zyrouge** 2023-07-31 17:31 UTC
Labels: bug, priority: high
