### ISSUE TITLE
[Feature Request] i want to add my own lyrics and add edit button on details of music and add some delete option, add this 3 features

### ISSUE THREAD

**Issue by meguccibruh** [zyrouge/symphony#167] opened 2023-05-29 03:28 UTC
### Checklist

-   [ ] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

**Comment by zyrouge** [comment] 2023-05-29 04:08
Duplicate of #72 and #159.

**Closed by zyrouge** 2023-05-29 04:08 UTC
Labels: enhancement
