### ISSUE TITLE
[Bug] Skip and previous track doesn't work via Pebble Watch

### ISSUE THREAD

**Issue by glcwinter** [zyrouge/symphony#189] opened 2023-06-10 20:52 UTC
### Description

You can't skip and move to previous track on Pebble Watch.

### Steps to Reproduce

1. Open default music control app on Pebble
2. Press forward or back button

**Comment by zyrouge** [comment] 2023-06-11 12:43
I cannot test this since I don't have any smart watch to check this.

**Comment by glcwinter** [comment] 2023-06-12 08:24
> I cannot test this since I don't have any smart watch. Unless I find out the cause I cannot look into possible solutions.

Friend of mine told me that "this happens because the player ignores avrcp commands"

**Comment by zyrouge** [comment] 2023-06-12 13:53
> > I cannot test this since I don't have any smart watch. Unless I find out the cause I cannot look into possible solutions.
> 
> Friend of mine told me that "this happens because the player ignores avrcp commands". Maybe this would help. Otherwise I'm open for testing anything!

Those are abstracted by Android API. As far as I know bluetooth commands from bluetooth headphones seem to be working. You could use the logs from your mobile to see what kind of event occurs. This could be used to know what's actually happening.

**Comment by glcwinter** [comment] 2023-06-12 17:18
> > > I cannot test this since I don't have any smart watch. Unless I find out the cause I cannot look into possible solutions.
> > 
> > 
> > Friend of mine told me that "this happens because the player ignores avrcp commands". Maybe this would help. Otherwise I'm open for testing anything!
> 
> Those are abstracted by Android API. As far as I know bluetooth commands from bluetooth headphones seem to be working. You could use the logs from your mobile to see what kind of event occurs. This could be used to know what's actually happening.

![image](https://github.com/zyrouge/symphony/assets/68323010/44909f6e-9c8d-4518-ac70-6bb837ca17d6)
Hello again, I used the logs from my mobile to see what kind of event occurs

**Comment by zyrouge** [comment] 2023-06-12 18:13
I guess the app doesn't receive or handle the event. Possibly handling [this](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_MEDIA_SKIP_BACKWARD) event could solve this, but I'm not 100% sure. Those logs don't quite say how android handled it (for example handled as a "skip media button" or "custom command"). Might need to more information if that doesn't fix that.

**Comment by fillwithjoy1** [comment] 2023-08-07 01:05
Garmin watch user over here - no problems on my end. I also tested forward media and backward media which all work as well. Maybe Pebble has a weird custom implementation that just doesn't work nowadays.

**Comment by zyrouge** [comment] 2023-12-04 17:09
Unfortunately I'll have to close this since I personally cannot test it. Any PRs will be appreciated.

**Closed by zyrouge** 2023-12-04 17:09 UTC
Labels: type: bug, state: wont fix

**Comment by fillwithjoy1** [comment] 2023-12-10 01:29
you realize marking this as closed, means that the issue is resolved and most potential devs may not notice the closed issues with the tags: help wanted...

**Comment by zyrouge** [comment] 2023-12-10 02:10
> you realize marking this as closed, means that the issue is resolved and most potential devs may not notice the closed issues with the tags: help wanted...

Keeping issues open for months just clutters up the whole issues tab. I'll be closing this as unplanned. Developers would probably read the thread if they find this issue to be true.
