### ISSUE TITLE
[Bug] App stops responding when searching for song name

### ISSUE THREAD

**Issue by SunBreaker1** [zyrouge/symphony#104] opened 2023-03-29 20:01 UTC
I can only get a few letters in before the app stops responding to inputs of any kind.

Even after closing the app from active apps, the app will not respond. 

It will only reset and respond after the phone gives "(insert app name) has stopped responding."

But the app will immediately "break" when trying to search again.

**Comment by zyrouge** [comment] 2023-03-30 03:02
Are you on the latest version? This was fixed before, and I don't face this issue anymore.

**Comment by SunBreaker1** [comment] 2023-03-30 06:29
> Are you on the latest version? This was fixed before, and I don't face this issue anymore.

Yup latest. While it doesn't happen all the time, it did happen multiple times back to back, and then stopped happening. But seems to happen time to time.![Screenshot_20230330_072849_Symphony.jpg](https://user-images.githubusercontent.com/85519676/228748886-e683075b-5cf7-46e7-8284-7acb105e32fb.jpg)

**Comment by zyrouge** [comment] 2023-03-31 16:18
Could you upload a clip of it happening? I am unable to reproduce this issue no matter what I try. This might be specific to some devices.

**Comment by SunBreaker1** [comment] 2023-03-31 17:40
> Could you upload a clip of it happening? I am unable to reproduce this issue no matter what I try. This might be specific to some devices.

https://user-images.githubusercontent.com/85519676/229191556-eda53cd2-4507-46d0-b9f7-9fa04dd57cdd.mp4

S23+ One UI 5.1

**Comment by SunBreaker1** [comment] 2023-04-08 21:02
This is happening when I cold open the app, not sure if this can be related to the fact that I have over 2k songs across 180 folders, or what?
@zyrouge ![Screenshot_20230408_220007_Symphony.jpg](https://user-images.githubusercontent.com/85519676/230742375-e62cba4e-037c-4c25-af21-7b5f347082fb.jpg)

**Comment by zyrouge** [comment] 2023-04-09 04:23
I'm pretty sure what the issue is, both have a common problem and a common solution.

**Comment by zyrouge** [comment] 2023-04-12 16:38
Fixed as of v2023.4.82, let me know if you still face this issue.

**Closed by zyrouge** 2023-04-12 16:38 UTC
Labels: bug, priority: high
